export const TemplateAssets = [
  { title: "럼다 댄스", videoUrl: "/app/videos/1. Rumba_960.mp4" },
  { title: "웨이브 댄스", videoUrl: "/app/videos/3. Wave_960.mp4" },
  { title: "턴", videoUrl: "/app/videos/4. Turn_960.mp4" },
  { title: "로봇", videoUrl: "/app/videos/5. Robot_960.mp4" },
  { title: "스탭", videoUrl: "/app/videos/6. Step_960.mp4" },
  { title: "강남 스타일", videoUrl: "/app/videos/DrHong_960_Full.mp4" },
  { title: "Seven", videoUrl: "/app/videos/Seven_960_Cut.mp4" },
  { title: "할 말이 없네", videoUrl: "/app/videos/DrHong_960_Full.mp4" },
  { title: "농협은행", videoUrl: "/app/videos/Bank_960_Full.mp4" },
  { title: "텃", videoUrl: "/app/videos/7. Tut_960.mp4" },
  { title: "힙합", videoUrl: "/app/videos/8. HipHop.mp4" },
  { title: "붐", videoUrl: "/app/videos/9. Boom_960.mp4" },
  { title: "다운", videoUrl: "/app/videos/10. Down_960.mp4" },
];
